# about captcha image
IMAGE_HEIGHT = 50
IMAGE_WIDTH = 200
#CHAR_SETS = 'abcdefghijklmnpqrstuvwxyz123456789ABCDEFGHIJKLMNPQRSTUVWXYZ'
#CHAR_SETS = '123456789ABCDEFGHIJKLMNPQRSTUVWXYZ'
CHAR_SETS = '3456789ABCDEHJKMNOPRSTUVWXYZ'
CLASSES_NUM = len(CHAR_SETS)
CHARS_NUM = 6
# for train
RECORD_DIR = './data'
TRAIN_FILE = 'train-6.tfrecords'
VALID_FILE = 'valid-6.tfrecords'
